Basic Jason integration with `flutter_webrtc` library
instrumentisto/medea-jason pull request #10
Opened 2021-10-14 11:18 UTC by evdokimovs

## Synopsis

Это PR из цикла задач по интеграции Jason'а в Flutter Android. В рамках этой задачи, были добавлены базовое взаимодействие Jason'а с `flutter_webrtc`.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has `k::` labels applied
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [x] FCM (final commit message) is posted
    - [x] and approved
- [x] [Review][l:2] is completed and changes are approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] `Draft: ` prefix is removed
    - [x] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2021-11-08 11:53 UTC, alexlapa requested changes
@evdokimovs ,

Discussed, added todos.

2021-11-09 11:44 UTC, alexlapa approved these changes
@evdokimovs ,

LGTM, передавайте tyranron'у как CI'ка докрутиться.

2021-11-09 14:50 UTC, evdokimovs commented
@alexlapa , @tyranron ,

Откуда вытекает проблема с `wasm-pack`'ом до конца не ясно. Но проблема не на нашей стороне, поскольку тоже самое происходит при попытке билда пустой библиотеки в Docker'е. Можно посмотреть в репозитории [evdokimovs/wasm-pack-segfault][1].

Также, закинул issue в wasm-pack: [rustwasm/wasm-pack#1079][1]

[1]: https://github.com/evdokimovs/wasm-pack-segfault
[2]: https://togithub.com/rustwasm/wasm-pack/issues/1079

2021-11-10 11:42 UTC, tyranron approved these changes

2021-11-10 11:52 UTC, merged