Integration with flutter_webrtc
instrumentisto/medea-jason pull request #12
Opened 2021-10-29 16:43 UTC by evdokimovs

## Synopsis

Это PR из цикла задач по интеграции Jason'а в Flutter Android. В рамках этой задачи, были добавлены оставшиеся биндинги для `flutter_webrtc`. В некоторых местах используются заглушки, это связано с тем, что не весь нужный функционал реализован в `flutter_webrtc` на данный момент. Эти заглушки будут заменены на реальные вызовы `flutter_webrtc` функций после его переработки. На этой ветке базово работают звонки на Android'е.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has `k::` labels applied
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [x] FCM (final commit message) is posted
    - [x] and approved
- [x] [Review][l:2] is completed and changes are approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] `Draft: ` prefix is removed
    - [x] All temporary labels are removed
    - [x] `flutter-webrtc` dependency switched back to `master` branch

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2021-11-01 10:50 UTC, evdokimovs commented
## FCM

```
Integration with flutter_webrtc (#12)

- add bindings for Transport, MediaDevices, Constraints, InputDeviceInfo
```

2021-11-01 10:52 UTC, evdokimovs commented
E2E тесты и Flutter тесты падают на CI, у меня на локалке все прокрутилось нормально.

2021-12-17 12:58 UTC, alexlapa requested changes
@evdokimovs ,

Discussed, added todos.

2021-12-20 11:32 UTC, evdokimovs commented
@alexlapa ,

Изменения по удалению `Transceiver::is_stopped` пришлось откатить, поскольку стейт `Stopped` еще не завезли в `web_sys::TransceiverDirection`.

2021-12-21 16:46 UTC, alexlapa approved these changes
@evdokimovs ,

От меня LGTM, перепроверьте что все работает, пожалуйста, и, если все ок - передавайте tyranron'у.

2021-12-22 11:37 UTC, tyranron requested changes

2021-12-22 11:41 UTC, tyranron commented on flutter/lib/src/native/platform/transport.dart
> +void _send(IOWebSocketChannel ws, Pointer<Utf8> message) {
Also, should we use `IOWebSocketChannel` which is just a wrapper over [`dart:io.WebSocket`](https://api.dart.dev/stable/dart-io/WebSocket-class.html)? Wouldn't be using raw `WebSocket` sufficient enough without requiring third-party deps?

2021-12-22 18:22 UTC, alexlapa commented on flutter/lib/src/native/platform/transport.dart
> +class BufferedWebSocket {
@evdokimovs ,

В смысле между созданием сокета и моментмо как раст на него подпишется успевают дойти сообщения?

Может сразу в `connect` прокидывать `onMessage` и `onClose` каллбеки?

2021-12-22 22:10 UTC, evdokimovs commented on flutter/lib/src/native/platform/transport.dart
> +class BufferedWebSocket {
@alexlapa ,

И правда перемудрил. В нашем случае это и правда более удачный вариант. Запушил эти изменения.

2021-12-23 10:55 UTC, alexlapa approved these changes

2021-12-24 10:12 UTC, tyranron approved these changes

2021-12-24 12:33 UTC, merged