Draft: Fix Callback memory leak
instrumentisto/medea-jason pull request #13
Opened 2021-11-01 11:49 UTC by evdokimovs

## Synopsis

Этот PR фиксит утечку памяти не `FnOnce` `Callback`'ов. Логика очистки построена на Дартовском механизме FFI финализаторов ([dart-lang/sdk#35770](https://togithub.com/dart-lang/sdk/issues/35770)).

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has `k::` labels applied
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [ ] FCM (final commit message) is posted
    - [ ] and approved
- [ ] [Review][l:2] is completed and changes are approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] `Draft: ` prefix is removed
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2021-11-01 11:49 UTC, evdokimovs commented
## FCM

```
Fix Callback memory leak (#13)
```

2021-12-16 08:41 UTC, alexlapa requested changes
@evdokimovs ,

Гляньте что с CI'кой, пожалуйста. Что `medea-demo-edge` падает помню.

2021-12-16 11:11 UTC, evdokimovs commented
@alexlapa ,

Откатил версию geckodriver'а, поскольку в версии 0.30.0 поломали работу `--host 0.0.0.0`. Вот issue по этой проблеме: [mozilla/geckodriver#1935][1].

[1]: https://togithub.com/mozilla/geckodriver/issues/1935

2021-12-16 13:19 UTC, alexlapa approved these changes

2021-12-16 14:14 UTC, tyranron approved these changes

2021-12-16 14:28 UTC, merged