Draft: Implement macro for generating code of Dart functions registration
instrumentisto/medea-jason pull request #14
Opened 2021-11-11 14:31 UTC by evdokimovs

## Synopsis

Этот PR реализует макрос `extern_dart!`, который генерирует код для функций регистрации Dart функций, а также обертки для вызова этого кода.

### Текущий синтаксис макроса

```rust
extern_dart! {
    // Code will be generated in the 'sys' module, also you can
    // control visibility of this module with visibility
    // modifier ('pub').
    mod sys {
        use std::ptr;

        use dart_sys::Dart_Handle;

        // Required line of code which sets prefix of the
        // registering function which should be called by
        // Dart side for registration.
        //
        // In this case, extern_dart! macro will generate
        // extern "C" functions with
        // "register_PeerConnection__create_offer" name.
        extern_prefix!(PeerConnection);

        // This documentation will be injected to the generated
        // extern function caller:

        /// Creates new offer in the provided `PeerConnection`
        ///
        /// Returns created SDP offer.
        unsafe fn create_offer(peer: Dart_Handle) -> ptr::NonNull<c_char>;

        /// Creates new answer in the provided `PeerConnection`
        ///
        /// Returns created SDP answer.
        unsafe fn create_answer(peer: Dart_Handle) -> ptr::NonNull<c_char>;
    }
}
```

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has `k::` labels applied
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [ ] CHANGELOG entry is added (if required)
- [ ] FCM (final commit message) is posted
    - [ ] and approved
- [ ] [Review][l:2] is completed and changes are approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] `Draft: ` prefix is removed
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2021-11-11 14:34 UTC, evdokimovs commented
## FCM

```
Implement macro for generating code of Dart functions registration (#14)

- add `extern_dart!` macro
```

2021-11-15 10:45 UTC, alexlapa commented
@tyranron ,

Тут пара мелочей осталась и пойдет на ревью.

Хочу обозначить изменения по сравнению с изначальным дизайном и мотивацию:
1. Решили не делать через attribute-like macro, так как атрибуты, по хорошему, принято вешать на валидный растовский код, а он у нас в любом случае невалидный получается.
2.  `MaybeUninit` vs `Option`: оставили `Option`'ы так как лучше ковырять паники чем сегфолты. `MaybeUninit` не стремно использовать только если мы можем гарантировать, что он таки init, что без генерации дартовского кода не особо получится. Существуют полумеры, конечно. 
3. Одна `register_PeerConnection` функция vs много `register_PeerConnection_*`: решили, что нарушеный порядок аргументов искать будет сложнее чем обращение к незарегистрированой функции, тоже segfault vs panic, по сути.
4. `impl PeerConnection` vs `mod peer_connection`: второй вариант тупо проще и больше похож на валидный код, просто бахаем все в модуль, наружу ничего лишнего не торчит, не надо делать анемичные структуры или трейты с дефолтными методами.

2021-11-15 15:12 UTC, tyranron commented
@alexlapa 

> 1. Решили не делать через attribute-like macro, так как атрибуты, по хорошему, принято вешать на валидный растовский код, а он у нас в любом случае невалидный получается.

What is wrong with making it valid? With function-like macro you loose IDE assist. We can avoid inventing something new ad just look [what `cxx` does](https://cxx.rs/extern-rust.html#extern-rust).
 
This is valid Rust syntax.
```rust
#[dart::bridge]
mod peer_connection {
    extern "C" {
        fn create_offer (peer: Dart_Handle) -> ptr::NonNull<c_char>;
        fn create_answer(peer: Dart_Handle) -> ptr::NonNull<c_char>;
    }
}
```

> 2. MaybeUninit vs Option: оставили Option'ы так как лучше ковырять паники чем сегфолты. MaybeUninit не стремно использовать только если мы можем гарантировать, что он таки init, что без генерации дартовского кода не особо получится. Существуют полумеры, конечно.

The point is that this is not something user-facing. So, we _can_ guarantee it. Either with tests or codegen. If it's not - it's an implementation bug. `MaybeUninit` will simplify panic reasoning in the code.

> 3. Одна register_PeerConnection функция vs много register_PeerConnection_*: решили, что нарушеный порядок аргументов искать будет сложнее чем обращение к незарегистрированой функции, тоже segfault vs panic, по сути.

This can be solved with enforcing alphabetical order, optionally covered by test/lint. Forgetting adding a function call is more subtle thaen forgetting adding a function argument, no?

And, finally, why we just don't generate the relative Dart code in the same proc-macro? Maybe either feature-gated, or `build.rs` based.

> 4. impl PeerConnection vs mod peer_connection: второй вариант тупо проще и больше похож на валидный код, просто бахаем все в модуль, наружу ничего лишнего не торчит, не надо делать анемичные структуры или трейты с дефолтными методами.

I'd vote for having both, but it's OK, having `mod` should be enough.

2021-11-16 14:45 UTC, alexlapa requested changes
> And, finally, why we just don't generate the relative Dart code in the same proc-macro?

Implement as discussed.

2021-11-19 07:51 UTC, alexlapa requested changes
@evdokimovs ,

Вот с такими вот занятными ошибками падает:
```
../lib/src/native/platform/ice_candidate.g.dart:18:56: Error: fromFunction expects a static function as parameter. dart:ffi only supports calling static Dart functions from native code. Closures and tear-offs are not supported because they can capture context.
        Pointer.fromFunction<Pointer Function(Handle)>(sdpMid),
```

Можете на CI'ке [глянуть](https://github.com/instrumentisto/medea-jason/runs/4250835578?check_suite_focus=true).

Насколько я понимаю, дарт не позволяет нам в сигнатуре `registerFunction` указать что функции-аргументы являются статическими. Т.е. нам надо `Pointer.fromFunction` дергать сверху, там где эта функция лежит, и дарт может определить что эту функцию можно передать через FFI.

Т.е. registerFunction будет выглядеть вот так:

```dart
void registerFunction(
  DynamicLibrary dl, {
  required Pointer<NativeFunction<Handle Function(ForeignValue, ForeignValue, ForeignValue)>> init,
  required Pointer<NativeFunction<Pointer Function(Handle)>> candidate,
  required Pointer<NativeFunction<Pointer Function(Handle)>> sdpMLineIndex,
  required Pointer<NativeFunction<Pointer Function(Handle)>> sdpMid,
}) {
  dl.lookupFunction<
      Void Function(Pointer, Pointer, Pointer, Pointer),
      void Function(Pointer, Pointer, Pointer, Pointer)>('register_ice_candidate')(
    init,
    candidate,
    sdpMLineIndex,
    sdpMid,
  );
}
```

Ну и вызов вот такой:

```
  bridge.registerFunction(
    dl,
    init: Pointer.fromFunction(_new),
    candidate: Pointer.fromFunction(_candidate),
    sdpMLineIndex: Pointer.fromFunction(_sdpMLineIndex),
    sdpMid: Pointer.fromFunction(_sdpMid),
  );
```

2021-11-22 07:34 UTC, alexlapa approved these changes

2021-11-22 15:54 UTC, tyranron approved these changes

2021-11-22 16:30 UTC, merged