Add ICE candidate errors sending to a server
instrumentisto/medea-jason pull request #151
Opened 2024-02-14 21:46 UTC by evdokimovs

## Synopsis

Sometimes ICE candidate error can happen on `PeerConnection`, but it will be just client side error and we will not know that this is happened, and what exactly happened. This can lead to the silent bugs (bugs we don't know about) or hardly fixable bugs (because we're not having any info about them). So we need to somehow monitor this kind of errors (and similar errors in the future).

## Solution

Firstly, we need to introduce new `PeerMetrics` which will be used for monitoring errors which can happen on a `PeerConnection`. It will be called `PeerMetrics::PeerConnectionError`.

Then we need to listen for [`onicecandidateerror`][1] events on client and send this errors to the server in this `PeerMetrics`. At this moment, server will just print them in logs, but in the future some additional mechanisms can be added (like displaying count of them in metrics, or using some backup methods to interconnect users somehow differently).

When this PR was started, `web-sys` had no support for [`RTCPeerConnectionIceEvent`][1] type, so it was implemented, but currently it's not released feature, so it's required at this moment to use git version of `wasm-bindgen` and related crates. `wasm-bindgen` releases every month at 6th, so most likely we can switch to the crates.io version after 06.03.2024.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains issue reference
    - [x] Has type and `k::` labels applied
    - [x] Has assignee
- Before [review][l:4]:
    - [x] Documentation is updated (if required)
    - [x] Tests are updated (if required)
    - [x] Changes conform [code style][l:2]
    - [ ] [CHANGELOG entry][l:3] is added (if required)
    - [ ] FCM (final commit message) is posted or updated
    - [ ] [Draft mode][l:1] is removed
- [ ] [Review][l:4] is completed and changes are approved
    - [ ] FCM (final commit message) is approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: /CONTRIBUTING.md#code-style
[l:3]: /CHANGELOG.md
[l:4]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests
[1]: https://www.w3.org/TR/webrtc/#rtcpeerconnectioniceevent

2024-02-15 14:50 UTC, evdokimovs commented
## FCM

```
Add ICE candidate errors sending to a server (#151)

Additionally:
- use git version of web-sys
```

2024-02-16 16:49 UTC, tyranron requested changes
After #152 I was unable to run `make cargo.gen.bridge` due to Dart dependencies errors:
```
2024/02/16 18:42:04 [INFO] Phase: Generate Dart code
2024/02/16 18:42:04 [ERROR] Fatal error encountered. Rerun with RUST_BACKTRACE=1 or RUST_BACKTRACE=full for more details.
Error: External command failure.
Please update version of ffigen in your dev_dependencies. (version >=8.0.0, <10.0.0)

Caused by:
    Please update version of ffigen in your dev_dependencies. (version >=8.0.0, <10.0.0)
make: *** [cargo.gen.bridge] Error 1
```

@evdokimovs please, resolve and regenerate the files properly.

2024-02-19 11:09 UTC, evdokimovs commented
@tyranron ,

Temporary pinned version of `ffigen` to `9.0.0` (supported both by `flutter_gherkin` and `flutter_rust_bridge`) until FRB updates. PR in FRB for this is already exists, and should be merged soon.

2024-02-19 15:11 UTC, tyranron approved these changes

2024-02-19 15:14 UTC, merged