Upgrade flutter_rust_bridge to v2.2.0
instrumentisto/medea-jason pull request #182
Opened 2024-08-20 11:31 UTC by alexlapa

## Synopsis

Upgrade `flutter_rust_bridge` to [v2.2.0](https://github.com/fzyzcjy/flutter_rust_bridge/blob/master/CHANGELOG.md#220)

## Checklist

- Created PR:
    - [ ] In [draft mode][l:1]
    - [ ] Name contains issue reference
    - [ ] Has type and `k::` labels applied
    - [ ] Has assignee
- Before [review][l:4]:
    - [ ] Documentation is updated (if required)
    - [ ] Tests are updated (if required)
    - [ ] Changes conform [code style][l:2]
    - [ ] [CHANGELOG entry][l:3] is added (if required)
    - [ ] FCM (final commit message) is posted or updated
    - [ ] [Draft mode][l:1] is removed
- [ ] [Review][l:4] is completed and changes are approved
    - [ ] FCM (final commit message) is approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] All temporary labels are removed

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: /CONTRIBUTING.md#code-style
[l:3]: /CHANGELOG.md
[l:4]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2024-08-21 07:48 UTC, alexlapa commented
FCM:

```md
Upgrade `flutter_rust_bridge` to 2.2.0 version (#182)
```

2024-08-21 15:07 UTC, tyranron commented on src/api/dart/api/room.rs
> +unsafe impl Sync for RoomHandle {}
@alexlapa @evdokimovs I don't like such approach. It's better than to wrap `core::RoomHandle` into `send_wrapper::SendWrapper` instead.

2024-08-21 16:39 UTC, tyranron approved these changes

2024-08-21 16:49 UTC, tyranron requested changes
@alexlapa seems that using `SendWrapper` indeed revealed some multi-thread usage, as `src/api/dart/api/local_media_track.rs:109:5` now panics.

Could you look into it?

2024-08-22 13:27 UTC, tyranron approved these changes

2024-08-22 13:45 UTC, merged