Draft: Add Jason and related crates source code
instrumentisto/medea-jason pull request #2
Opened 2021-08-18 02:58 UTC by evdokimovs

## Synopsis

We need to add source code of the Jason and all related crates.

Also, in this PR will be added CI spec with all needed for `medea-jason` steps.

## Solution

Move all needed source code into this repo, adapt old CI spec from the `medea` repository, fix outdated repo links in project files.

2021-08-18 22:57 UTC, evdokimovs commented
## FCM

```
Add Jason and related crates source code (#2)

- add medea-jason crate source code
- add Client and Control API crates source code
- add medea-macro and medea-reactive crates

Additionally:
- implement GitHub Actions spec
- fix Jason Flutter E2E tests running on minimal SDK version
- downgrade NDK to 21e
```

2021-08-19 15:11 UTC, alexlapa commented
@evdokimovs ,

Есть много упущений - надо более внимательно все перебрать.

2021-08-19 15:12 UTC, alexlapa requested changes
@evdokimovs ,

Есть много упущений - надо более внимательно все перебрать.

2021-08-25 06:53 UTC, alexlapa approved these changes

2021-08-25 15:27 UTC, tyranron approved these changes
## FCM

```
Migrate Jason and proto crates from Medea repository (#2)

- add `medea-jason` crate
- add Client and Control API crates source code
- add `medea-macro` and `medea-reactive` crates
- add `medea-demo` and its Helm chart and Docker image
- add `medea-control-mock-api` and its Docker image

Additionally:
- fix Jason Flutter E2E tests running on minimal SDK version
```

2021-08-25 15:29 UTC, merged