Draft: Implement output audio management
instrumentisto/medea-jason pull request #29
Opened 2022-03-09 10:22 UTC by evdokimovs

## Synopsis

Этот PR реализует функционал переключения output audio треков в Jason'е.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has `k::` labels applied
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [ ] FCM (final commit message) is posted
    - [ ] and approved
- [ ] [Review][l:2] is completed and changes are approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] `Draft: ` prefix is removed
    - [ ] All temporary labels are removed
    - [ ] `flutter-webrtc` dependency switched back to `master` branch

[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2022-03-10 10:38 UTC, evdokimovs commented
## FCM

```
Implement output audio management (#29)

- add `MediaManagerHandle.set_output_audio_id`
- rename `InputDeviceInfo` to the `MediaDeviceInfo`
- now `MediaManagerHandle.enumerate_devices` returns `audiooutput` devices
```

2022-03-11 16:35 UTC, alexlapa approved these changes

2022-03-14 08:35 UTC, tyranron requested changes
Fix CI.

2022-03-14 13:20 UTC, tyranron approved these changes

2022-03-14 14:15 UTC, merged