Add windows target
instrumentisto/medea-jason pull request #33
Opened 2022-03-21 09:40 UTC by rogurotus

## Synopsis

Add windows target 

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has `k::` labels applied
    - [x] Has assignee
- [ ] Documentation is updated (if required)
- [ ] Tests are updated (if required)
- [ ] Changes conform code style
- [ ] CHANGELOG entry is added (if required)
- [ ] FCM (final commit message) is posted
    - [ ] and approved
- [ ] [Review][l:2] is completed and changes are approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] `Draft: ` prefix is removed
    - [ ] All temporary labels are removed
  
[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2022-03-22 10:40 UTC, rogurotus commented
## FCM

```
Add windows target (#33)
```

2022-03-25 10:37 UTC, alexlapa approved these changes

2022-03-25 10:39 UTC, alexlapa commented
@tyranron ,

По закомменченым тестам: есть бага, уже разобрались что именно происходит, evdokimovs сразу после слива этой задачи ей займется. Единственное, что не ясно, это почему она стреляет только в Linux тестах и только на CI.

2022-03-28 10:56 UTC, tyranron requested changes
I've reworked the toolchain more properly, but there are still test failures. Please, fix.

2022-03-28 14:38 UTC, alexlapa commented
@tyranron ,

Ну там сейчас только тесты на андроиде зависли, но это уже другая история, будем разбираться отдельно.

2022-03-28 14:51 UTC, tyranron approved these changes

2022-03-28 14:52 UTC, merged