Fix string leak
instrumentisto/medea-jason pull request #69
Opened 2022-06-23 16:03 UTC by rogurotus

## Synopsis

Some strings leak, also `register_free_dart_native_string` is not initialized in Dart

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has `k::` labels applied
    - [x] Has assignee
- [x] Documentation is updated (if required)
- [x] Tests are updated (if required)
- [x] Changes conform code style
- [x] CHANGELOG entry is added (if required)
- [x] FCM (final commit message) is posted
    - [x] and approved
- [x] [Review][l:2] is completed and changes are approved
- Before merge:
    - [x] Milestone is set
    - [x] PR's name and description are correct and up-to-date
    - [x] `Draft: ` prefix is removed
    - [x] All temporary labels are removed
  
[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2022-07-12 13:37 UTC, alexlapa requested changes
@rogurotus ,

Regarding the strings memory management there is quite a mess right now, maybe we can refactor this in a way that `DartValue` explicitly contains the string origin. Something like this:

```
pub enum MemoryOwner {
    Rust,
    Dart
}

pub enum DartValue {
    ...
    /// Native string.
    String(ptr::NonNull<c_char>, MemoryOwner),
   ...
}


impl Drop for DartValue {
    fn drop(&mut self) {
        match self {
            DartValue::Int(_) | DartValue::Handle(_) | DartValue::Ptr(_) | DartValue::None => {}
            DartValue::String(ptr, MemoryOwner::Dart) => {
                unsafe { free_dart_native_string(*ptr); }
            }
            DartValue::String(ptr, MemoryOwner::Rust) => {
                unsafe { drop(CString::from_raw(ptr.as_ptr())); }
            }
        }
    }
}
```

2022-07-15 12:23 UTC, alexlapa commented
FCM:

```
Fix string leak in FFI glue (#69)
```

2022-07-15 12:24 UTC, alexlapa approved these changes

2022-07-15 13:30 UTC, tyranron approved these changes

2022-07-15 13:52 UTC, merged