add medea_jason.wasm hash parametr
instrumentisto/medea-jason pull request #83
Opened 2022-09-07 15:03 UTC by rogurotus

## Synopsis

A browser cache ignores updating `medea_jason_bg.wasm`.

## Checklist

- Created PR:
    - [x] In [draft mode][l:1]
    - [x] Name contains `Draft: ` prefix
    - [x] Name contains issue reference
    - [x] Has `k::` labels applied
    - [x] Has assignee
- [ ] Documentation is updated (if required)
- [ ] Tests are updated (if required)
- [ ] Changes conform code style
- [ ] CHANGELOG entry is added (if required)
- [ ] FCM (final commit message) is posted
    - [ ] and approved
- [ ] [Review][l:2] is completed and changes are approved
- Before merge:
    - [ ] Milestone is set
    - [ ] PR's name and description are correct and up-to-date
    - [ ] `Draft: ` prefix is removed
    - [ ] All temporary labels are removed
  
[l:1]: https://help.github.com/en/articles/about-pull-requests#draft-pull-requests
[l:2]: https://help.github.com/en/articles/reviewing-changes-in-pull-requests

2022-09-07 15:04 UTC, rogurotus commented
FCM:

```
add medea_jason.wasm hash parametr (#83)
```

2022-11-30 05:58 UTC, alexlapa requested changes

2022-11-30 05:58 UTC, alexlapa commented on Makefile
> +	sed -i "s/medea_jason_bg.wasm/medea_jason_bg.wasm?\
This doesn't work, `sha256` invocation does not wait for build to finish for some reason:
```
$ make flutter.web.assets
sha256sum: flutter/assets/pkg/medea_jason_bg.wasm: No such file or directory
wasm-pack build -d flutter/assets/pkg --no-typescript -t web
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.09s
``` 

So the resulting `medea_jason.js` looks like this:

```js
async function init(input) {
    if (typeof input === 'undefined') {
        input = new URL('medea_jason_bg.wasm?', import.meta.url);
    }
...
```

2022-12-30 19:38 UTC, alexlapa approved these changes

2023-01-02 13:56 UTC, tyranron approved these changes

2023-01-02 17:09 UTC, merged